# @package _group_

# Hydra will instantiate this class as the trainer
_target_: lightning.pytorch.trainer.Trainer

# Where Lightning saves logs / checkpoints if the logger
# doesn’t specify its own root directory
default_root_dir: ${paths.output_dir}

# Epoch limits
min_epochs: 1          # prevents early stopping in the first epoch
max_epochs: 100

# Device setup – single-GPU by default; other yaml files
# (e.g. multi_gpu.yaml) can override `devices`
accelerator: gpu
devices: 1

# Mixed precision (commented out; enable if you want fp16/bf16)
# precision: 16

# Validation settings
check_val_every_n_epoch: 1
num_sanity_val_steps: 0

# Make training deterministic / reproducible
deterministic: True